### ISSUE TITLE
handle report_sources/_archive/ to store, not compile old reports 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#12]
It would be useful to have an archiving mechanism for old reports. One way would be have an `_archive/` folder in `report_sources/` which will be ignored by all functions ineracting with `Rmd` files.

**Comment by zkamvar** [comment]
So, like a mechanism by which the user targets reports that were created before a certain day as archived?

**Comment by zkamvar** [comment]
e.g.

```r
archive_reports("test", before = Sys.Date() - 2) # archive all reports older than two days ago
compile_reports(all = TRUE) # would skip over the archived ones
```

**Comment by zkamvar** [comment]
bump

**Comment by zkamvar** [comment]
I need more information before I can get started on this.

**Comment by zkamvar** [comment]
Just a reminder that I need more information about this. I'm not terribly familiar with the report factory structure, so it's not clear what's needed.

Questions:

1. What does the current filetree look like for a project where some files need to be archived?
2. Will the user simply shove folders that need to be archived in `archive/` or should there be a command-line interface for this?

I ask these questions because lot of time will be wasted if I template something that was completely different than what you envision.

**Comment by thibautjombart** [comment]
Small expl below. It's a matter of being able to place report in `report_sources/_archive` which are then 'disabled', i.e. the factory does not list them by default when calling `list_reports()`, and `update_reports()` won't compile them.

```r
library(reportfactory)
new_factory()
dir.create(file.path("report_sources", "_archive"))
file.copy(file.path("report_sources", list_reports()[1]), 
          file.path("report_sources", "_archive", "old_stuff_2019-01-31.Rmd"))
list_reports

list_reports()
[1] "old_stuff_2019-01-31.Rmd"      "example_report_2019-01-31.Rmd"
> 
```

Details of modifications would entail:

* change `list_reports()` so that it ignores reports in `report_sources/_archive/` by default, maybe adding an argument `ignore_archive = TRUE` to the function; when `FALSE`, the printing should clearly show which reports are archived

* change `update_reports()` so that it always ignores reports in `report_sources/_archive/` 

* archive_reports(until)`: archive reports (move them to `report_sources/_archive/`) with a date anterior to `until` (which needs to be a valid date)

Lemme know if unclear.

**Comment by zkamvar** [comment]
> with a date anterior to until (which needs to be a valid date)

e.g. `archive_reports("2019-05-15")` will archive all the reports that have a date on or before 15 May?

**Comment by thibautjombart** [comment]
Dassit! :)
