### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by zkamvar** [reconhub/reportfactory#14]
There is a lot of dead code within this repository. By dead code, I mean valid R code that has been commented out. A perfect example of this is the entire file for last_reports.R:

https://github.com/reconhub/reportfactory/blob/0eaed4bf9ff2977cf7679f38d02ff1cf1e8ab015/R/last_reports.R#L1-L18

**Comment by sgetalbo** [comment]
I will work through this as part of my Locke Data general code review for report factory on my dev branch. Is it your intention that it is just deleted, or uncommented and made functioning?

**Comment by zkamvar** [comment]
Given that the package currently is working in production, I would assume that dead code is no longer needed, so deletion is preferable.

**Comment by sgetalbo** [comment]
This issue can now be closed following the Locke Data Review.
