### ISSUE TITLE
use orderly as a backend

### ISSUE THREAD

**Issue by zkamvar** [reconhub/reportfactory#17]
I think this project could benefit quite a bit from using orderly as a backend to render and validate reports and outputs. 

I agree that orderly isn't suited for the field epidemiologist who just wants to get a report to run, but I think we can leverage its workflow and output validation features under the hood. If we do this, then we can take advantage of the fact that orderly is currently well-tested and is being used throughout imperial. The only thing it lacks currently is good documentation.

**Comment by zkamvar** [comment]
Link to orderly because I always forget what account it lives under: https://github.com/vimc/orderly

**Comment by thibautjombart** [comment]
The initial design choice of *orderly* - separate `yaml` file and inability to compile `Rmd` as standalone documents was a deal-breaker for field use. Unless this has changed, I think we cannot use it as backend. We should weight pros/cons thoroughly before rewriting the package, and given its current use in the field, I'd say this is out of question for the 6 coming months.
