### ISSUE TITLE
Check Rmds for update in code and rename or create new file

### ISSUE THREAD

**Issue by jarvisc1** [reconhub/reportfactory#18]
It would be nice if the date of the report corresponded to the either the date it was run or perhaps better the date of the data it uses. 

Currently in Goma we are dating the Rmds based on when the code in a report is changed. This is useful for us to track the evolution of the code but means that the report outputs are dated based on the code they use rather than on the date they are run. This has been confusing for the end users of the reports as since code has become stable the reports seem as if they are old.

This could be achieved by having the file automatically renamed based on the data or the data. A check could be run on the Rmd file to see if the code has changed and if so the file is saved as a new version and the old is kept and automatically moved to an _archive folder.

**Comment by zkamvar** [comment]
Hi @jarvisc1,

I think what you are describing is the current model of [orderly](https://vimc.github.io/orderly/) and I have actually suggested using orderly as a backend (#17), which I think could work, but requires basically a rewrite of the entire package internals (which I'm not opposed to, but this does take time).

**Comment by thibautjombart** [comment]
Replied on the other issue. At some point it is fine to decide a given feature belongs elsewhere. I fear the initial design choices will be hard to reconcile, but let see.
