### ISSUE TITLE
Add encoding argument, default to UTF-8

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#19]
It would be very useful to add an `encoding` argument to `compile_report` and `update_reports`, passed on to `rmarkdown::render()`, defaulting to `"UTF-8"`.

**Comment by zkamvar** [comment]
Rmarkdown 1.13 now only supports UTF-8: https://cran.r-project.org/web/packages/rmarkdown/news/news.html

**Comment by thibautjombart** [comment]
May be worth putting it as a dependency then. Encoding problems have been a strong bottleneck when using the *reportfactory* across different computers, and the resulting errors are usually cryptic.

**Comment by thibautjombart** [comment]
I'm on it.

**Comment by thibautjombart** [comment]
closed via commit 311f71af4182ce043f9ca6c0b647a2dcf9834f45 and PR https://github.com/reconhub/reportfactory/pull/20
