### ISSUE TITLE
[Suggestion] Add section to README explaining choice of naming convention

### ISSUE THREAD

**Issue by RaoOfPhysics** [reconhub/reportfactory#4]
Thanks for the clear description in your `README`! I was wondering if you were open to the possibility of explaining the reason the particular convention of `[report_base_name]_[yyyy-mm-dd].Rmd` was chosen. Most people probably expect the date (in [ISO format](https://en.wikipedia.org/wiki/ISO_8601)) to be the leading element of filenames for easy sorting, but here, I'm guessing, it's better to lead with the base name so the files will all be clustered together and ordered by date/version. Is this correct?

I would be happy to make the change and submit a PR for your review.

**Comment by sgetalbo** [comment]
Locke Data Review - I agree that to non-RECON users this could use some clarity and if the assumption is correct, the README would benefit from this addition. 

If the assumption is incorrect it may be worthwhile adopting the date first naming convention.

**Comment by thibautjombart** [comment]
Naming conventions have now changed, with no date needed in file names.
