### ISSUE TITLE
find_file( ) function rationale

### ISSUE THREAD

**Issue by sgetalbo** [reconhub/reportfactory#48]
@thibautjombart Locke Data were hoping to get clarity on a few things and suggest some changes to the find_file function - it is fairly impenetrable to an outsider. Could you guide us on the following aspects and give us your thoughts on the proposed changes please? The rationale behind this even though it is an internal function is purely robustness. Your clarification will allow us to write the most appropriate tests :) 

For context - the original function is : 

```r
find_file <- function(x = NULL) {
  root <- rprojroot::find_root(rprojroot::has_file(".here"))
  if (!is.null(x) ) {
    out <- file.path(root, x)
  } else {
    out <- root
  }
  out
}
```

- [ ] Why is there code for handling the case where `x = NULL` ? As far as I can establish, the function is never called with the default argument. 

- [ ] It feels like the function name is not really meaningful/representative - would you be open to renaming to `append_root()`? 

- [ ] We envisage the improved function looking something like the following, what do you think? It should make the code more readable - but ultimately depends on the rationale for the NULL case. 

```r
append_root <- function(folder = NULL) {
 root <- rprojroot::find_root(rprojroot::has_file(".here"))
 if (is.null(folder) ) {
   return(root)
 }
 return(file.path(root, folder))
}
```

- [ ] Are you open to adding new package dependencies for testing - obviously lightweight-ness is a priority. We envisage using `mockery` in this instance. 

TIA!

**Comment by thibautjombart** [comment]
Hi there, 
thanks for this! Funny enough, I have just PR-ed https://github.com/reconhub/reportfactory/pull/49 and looked in puzzlement at the function myself. 

As you guessed, the function's aim was essentially to replicate `here::here()` in a package-robust way. I am happy with the renaming, which makes more sense than the current version. It would be good to add a couple of comments before the code too - by bad for not doing so in the first place.

**Comment by sgetalbo** [comment]
Following on from the catch up call today - as far as we can see, this file directly replicates `here::here()` 

It is LD's view that it would make more practical sense to implement that function instead - it is widely used, and is from a trusted CRAN repo. To keep the original function is duplicating effort as we would have to write tests etc and is possibly not the best use of our time. Given that `here` 's only dependency is `rprojroot` which is already a dependency of `reportfactory` it is in keeping with the requirement to keep dependencies low. Furthermore, bugs etc in `here::here` are likely to have been caught already. Once `here` is a dependency this may provide other opportunity to streamline the internal functions going forward. 

If the function were to do something slightly different then keeping `find_file()` would be appropriate but as far as I can see, it doesn't :)

**Comment by thibautjombart** [comment]
I was following the advice from `?here::here`: 
```
Details:

     This package is intended for interactive use only. Use
     ‘rprojroot::has_file()’ or the other functions in the ‘rprojroot’
     package for more control, or for package development.
```

I suspect the two functions may have slightly different behaviours, e.g. I think `here::here` will also pick up other files such as `.Rproj` or `.git` to identify the root?

**Comment by thibautjombart** [comment]
This has now been renamed to `factory_path` as of 8f173f257eecea193139e360399450fa1950bf56 ; the doc should be more explicit - it is basically an equivalent of `here::here()`
