### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#5]
I've just realised this was never put on CRAN. People may start needing it for field deployment. Would be great to have some external view on the whole thing. @zkamvar maybe?

**Comment by zkamvar** [comment]
I think I can assess this. I'll use rOpenSci's guidelines for review and either open an issue or pull request. Does that sound good for you?

**Comment by thibautjombart** [comment]
Awesome. thanks :) Actually could you use these guidelines:
https://www.repidemicsconsortium.org/resources/
and update whatever needs updating ;)

**Comment by zkamvar** [comment]
Got it!

**Comment by zkamvar** [comment]
Question: what's the timeline on getting this assessed?

**Comment by zkamvar** [comment]
I started on a review four months ago (https://github.com/reconhub/reportfactory/tree/znk-review), but that was right before everything went to hell. I will pick it up again, but I may have to start over since changes were made from when I started.

**Comment by sgetalbo** [comment]
Hey all - as part of the work with the Locke Data team, I'm going to pick this issue up today. Thanks @thibautjombart for the useful links and @zkamvar for starting points.

**Comment by zkamvar** [comment]
Thanks for getting on this @sgetalbo! I'll loop in @amygimma here as well as I believe she will be contributing to the package in the future.

**Comment by sgetalbo** [comment]
I think this issue can now be closed in favour of smaller issues being created to tackle individual aspects of CRAN readiness.
