### ISSUE TITLE
Add tools package as a dependency, refactor file ext/ base ext code throughout

### ISSUE THREAD

**Issue by amygimma** [reconhub/reportfactory#50]
* add "tools" package as a dependency
* refactor all code that greps for file name or ext to use `tools` functions. 

Example:

```r
foo <- unlist(outputs_only_filtered, use.names = FALSE)

# file extensions are within the expected set.
expect_setequal(tools::file_ext(foo), c("png", "csv"))
```

_Originally posted by @zkamvar in https://github.com/reconhub/reportfactory/pull/44_

**Comment by thibautjombart** [comment]
Should be sorted as of 8f173f257eecea193139e360399450fa1950bf56
