### ISSUE TITLE
filter_log should have an option to return only matching log entries with no params

### ISSUE THREAD

**Issue by amygimma** [reconhub/reportfactory#52]
Problem: 
Currently, `filter_log(file = "foo_2019_10_10.rmd", most_recent = TRUE)` returns the most recently compiled "foo_2019_10_10.html", regardless of whether or not params are passed. There is no way to return the most recent file that was compiled with no params.

Solution: 
`filter_log(file = "foo_2019_10_10.rmd", params = "empty", most_recent = TRUE)` should return only files compiled with no params. Default is `filter_log(file = "foo_2019_10_10.rmd", params = "any", most_recent = TRUE)`, which returns most recent matching source file regardless of params passed

```{r}
# Default: returns all entries that match the arguments, regardless of params
filter_log(params = "any")

# Option: returns only entries in which no params were passed to `compile_log` 
filter_log(params = "empty")

# Option: returns entries with matching params to the call `compile_log(quiet = TRUE, params = list("light = TRUE))` 
filter_log(quiet = TRUE, params = list("light" = TRUE))

```

**Comment by amygimma** [comment]
@thibautjombart how does this sound? want to make any tweaks to it before work starts?

**Comment by thibautjombart** [comment]
Logs are disabled in the CRAN version.
