### ISSUE TITLE
Make output of list_reports and list_outputs more user friendly

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#6]
For instance:

```
> reportfactory::list_reports()
[1] "alerts_2019-02-12.Rmd" "alerts_2019-02-13.Rmd" "alerts_2019-02-14.Rmd" "foobar_2018-01-01.Rmd"

```
Could acknowledge the hierarchical nature of the reports and be turned into:

```
> reportfactory::list_reports()
// report "alerts":
    versions: "2019-02-12", "2019-02-13", "2019-02-14"
// report "foobar":
    versions: "2018-01-01"
```
We probably want to have a bit of flexibility in terms of outputs, as I suspect the current ouput shape is used elsewhere in the code. One option would be:

- rename current `list_reports` into `list_rmds` or `list_sources`
- change `list_reports` to return a list with components named after the reports, each component being a list of dates, with a specific class for printing as above

@zkamvar lemme know what you think

**Comment by zkamvar** [comment]
One thing we could do is just call the character vector a 'punchcard' object and define `print()`, `as.list()` and `as.character()` methods for it where the `as.list()` separates the reports by name and `as.character()` returns the original vector.

**Comment by thibautjombart** [comment]
Sounds brilliant!

**Comment by thibautjombart** [comment]
Current version does improve the output. Closing for now as unsure this will be needed.
