### ISSUE TITLE
Add cleaner for content in report_sources 

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#7]
We should add a cleaning routine which would remove anything in `report_sources` which is not:

- `.Rmd` file
- `.R` file
- `README*`

Especially to get rid of temp hidden files e.g. `toto_2012-03-21.Rmd~` , folders storing outputs, `cache/` and suchlikes.

**Comment by zkamvar** [comment]
I can understand getting rid of anything related to emacs, but why would you want to remove `cache/` if they are tied to a specific report?

**Comment by thibautjombart** [comment]
Good point. Usually I only ever use `cache = TRUE` for intermediate compilation, but never for the final compilation as I have seen it being the source of a great many evil (which most new users won't know about). I guess that would be part of enforcing some good practices, but I am not sure there is a consensus that not using `cache` is a widely accepted one?

If we leave it: do we need to concern ourselves with `cache` collusion across different reports?

**Comment by zkamvar** [comment]
Given that you do not use cache in your workflows, you will be actively encouraging people to not use cache as well, so I don't think we need to concern ourselves with the question of leaving it or keeping it.

**Comment by thibautjombart** [comment]
All handled through `clean_report_sources()`.
