### ISSUE TITLE
gitignored outputs/ folder fails factory validation

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#72]
Please place an "x" in all the boxes that apply
---------------------------------------------

 - [x] I have the most recent version of reportfactory and R
 - [x] I have found a bug
 - [x] I have a [reproducible example](http://reprex.tidyverse.org/articles/reprex-dos-and-donts.html)
 - [ ] I want to request a new feature

--------

The fact that *outputs/* is gitignored means when cloning a factory from a git repos, the factory is no longer valid; I would recommend skipping checks on this folder, and creating it when running  `compile_reports()` if it does not exist? Here's a simulation, manually removing the folder:

``` r
library(reportfactory)

new_factory("toto")
file.remove("outputs")
#> [1] TRUE
validate_factory()
#> Error: Folder 'outputs' does not exist.  Have you renamed it by mistake?
```

<sup>Created on 2021-02-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

---------

**Comment by tjtnew** [comment]
Sounds sensible to create it with `compile_reports()` but wonder if we change the error to a `message` rather than remove the check altogether.  Perhaps
`message("Folder 'outputs' does not exist.  It will be created the first time 'compile_reports' is run")`
