### ISSUE TITLE
Output from reportfactory doesn't support French accents

### ISSUE THREAD

**Issue by pbkeating** [reconhub/reportfactory#8]
Hi @thibautjombart @zkamvar 

Minor, but it would be great if reportfactory outputs could include French accents.
If we directly knit an Rmd, then the  French accents appear normally, but not when we use the reportfactory.

Thibaut, I imagine that you are aware of this, but just worth mentioning.

Thanks,
P

**Comment by zkamvar** [comment]
Do you mean French accents in the text of the markdown?

**Comment by thibautjombart** [comment]
Nope, unaware of it, and was not happening on linux. The reportfactory calls `rmarkdown::render` which should not produce different outputs. Can you confirm this happens on exactly the same document and computer, and the OS used?

**Comment by pbkeating** [comment]
I am using windows and just tested the same document and the é appeared with knitting and not with the reportfactory

See attached for output from reportfactory and from direct knitting
<img width="608" alt="markdown_no_error" src="https://user-images.githubusercontent.com/20238915/56810486-b4a8e100-6836-11e9-9038-b3eec2e7072b.PNG">
<img width="596" alt="reportfactory_error" src="https://user-images.githubusercontent.com/20238915/56810487-b4a8e100-6836-11e9-9e22-2afc0e63123f.PNG">

**Comment by zkamvar** [comment]
I think RStudio may have the default encoding to UTF-8, but your computer has a different encoding.

does it work if you do `rmarkdown::render("document.Rmd", encoding = "UTF-8")`?

**Comment by pbkeating** [comment]
can I add that to reportfactory?

**Comment by zkamvar** [comment]
If this solution works, then yes, we should add this to reportfactory

**Comment by zkamvar** [comment]
actually, you might be able to just pass `encoding = "UTF-8"` to `compile_report()`

**Comment by pbkeating** [comment]
Success! Thanks a lot, Zhian!
