### ISSUE TITLE
name collision bug (urgent please thanks merci eurostar)

### ISSUE THREAD

**Issue by thibautjombart** [reconhub/reportfactory#9]
If several `Rmd` have similar names (one being the prefix of the other), compilation fails, I suspect because several paths are used where only one should be detected

To reproduce the issue:

1. `reportfactory::new_factory("test")`
2. outside R, go to the sources, make a copy of `example_report_2019-01-31.Rmd` called `foo_example_report_2019-01-31.Rmd` 
3. back in the R session, run:

```

> reportfactory::update_reports()  
/// compiling report: 'example_report_2019-01-31' 
/// compiling report: 'foo_example_report_2019-01-31' 
Error in tools::file_path_as_absolute(input) :
    'x' must be a single character string In addition: 
Warning message: 
In if (grepl(.shell_chars_regex, basename(input))) { :   the condition has length > 1 and only the first element will be used

```

**Comment by zkamvar** [comment]
Found a solution. Writing a test and I'll make a PR
